# Generated by Django 3.2.8 on 2021-12-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0002_auto_20211214_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='continent',
            new_name='continente',
        ),
    ]
